### ISSUE TITLE
E1600 there is only a silder and value option via automation for setting the 0 to 600W limit

### ISSUE THREAD

**Issue by Wingcom1** [thomluther/anker-solix-api#99]
Is it possible to set the limit from 0 to 800W via a variable or another sensor dynamically in case of an automation. The number.solarbank_e1600_system...   takes no values except from silder or manuell value. May be thats not an issue only a missing feature.

**Comment by thomluther** [comment]
Hi,
Not sure what you do, in my automation it works via a service. Here is an example snippet:
See number.set_value for number.sb_e1600_system_einspeisevorgabe
```
          - if:
              - condition: template
                value_template: "{{new_preset > actual_preset}}"
                alias: Testen dass neue Vorgabe größer als aktive Vorgabe
            then:
              - if:
                  - condition: state
                    entity_id: input_boolean.solarbank_erhohung_freigabe
                    state: "on"
                then:
                  - alias: Vorgabe erhöhen
                    service: number.set_value
                    data:
                      value: |
                        {{new_preset}}
                    target:
                      entity_id: number.sb_e1600_system_einspeisevorgabe
                    enabled: true
                  - alias: Logbuch Eintrag machen
                    service: logbook.log
                    data:
                      message: >
                        {{new_preset}} W bei {{consumption_median}} W
                        Hausverbrauch und {{grid}} W Netz
                      name: "Erhöhung Solarbank Vorgabe ({{mode}}):"
                      entity_id: switch.sb_e1600_erlaube_leistungsabgabe
                else:
                  - service: input_boolean.turn_on
                    target:
                      entity_id: input_boolean.solarbank_erhohung_freigabe
                    data: {}
              - alias: Vorgabetimer starten um Änderungen zu limitieren
                service: timer.start
                target:
                  entity_id: timer.solarbank_vorgabe
                data:
                  duration: "{{int(delay_minutes*60)}}"

```
